rem 服务端配置
excel2lua_final.py excel\Alliance_science.xls  ALLIANCE_SCIENCE_INFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_science.xls  ALLIANCE_SCIENCE_LV_STAR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_science.xls  ALLIANCE_SCIENCE_LV --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_shop.xls  ALLIANCE_ITEM_LIST --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Army.xls  ARMYINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Army.xls  ARMYSPECIALITY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Buff.xlsx  BUFF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD101 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD102 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD103 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD104 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD105 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD111 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD112 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD113 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD114 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD115 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD116 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD117 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD118 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD119 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD120 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD121 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD122 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD201 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD202 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD203 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD204 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD205 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD206 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILD301 --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILDINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  OPENGROUNDINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  MAPOBJNUM --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  CITYREFRESH --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  RELIC --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  RESOURCE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Treasure.xlsx  GEOCACHING --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Treasure.xlsx  GEOCACHINGCRIT --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  ITEM --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  PACKAGEDATA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Lord.xls  RANK --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Lord.xls  SKILL --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Lord.xls  HEAD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Mail.xlsx  MAILCOUNTINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Merchant.xlsx  MERCHANTCONFIG_AR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Merchant.xlsx  MERCHANTCONFIG_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Merchant.xlsx  MERCHANTTIME --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Npc.xls  NPC --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Npc.xls  NPCREWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Npc.xls  NPCFIRSTREWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Shop.xlsx  SHOP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Technology.xlsx  TECHNOLOGY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Vip.xlsx  VIP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Vip.xlsx  VIPLOGIN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Quest.xlsx  QUESTCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  ACTIVITY_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  ACTIVITY_EVENT_LIST --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  ACTIVITY_POINT_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  ACTIVITY_STAGE_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  ACTIVITY_TOTAL_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  LOGINREWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  TIMEREWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  INVITEAWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  REGISTERAWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  ATTACKEDAWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  RECHARGECONF_NORMAL --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  RECHARGE_ACTIVITYCONF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_ACTIVE_TIME --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_COMSUM --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_RECHARGE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  LOGINLOSINGGIFT --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Pyramid.xlsx  PYRAMID --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Pyramid.xlsx  PYRAMID_ITEM --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGPACKS --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGOFFICIAL --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_BASE_PROPERTY_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  FORGE_EQUIPMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  STRENGTHEN_EQUIPMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  REMAKE_EQUIPMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  REMAKE_EQUIPMENT_RATE_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_EXTRA_PROPERTY_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_MATERIAL_GROUP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_MATERIAL_FORMULA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  DISASSEMBLE_EQUIPMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  DISASSEMBLE_MATERIAL_GROUP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_POWER_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Luckygift.xlsx  LUCKYGIFT_AR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Luckygift.xlsx  LUCKYGIFT_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Rome_activity.xlsx  ROME_ACTIVITY_ARMYCONF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Rome_activity.xlsx  ROME_ACTIVITY_ARMYSCORE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Rome_activity.xlsx  ROME_ACTIVITY_LEVEL_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Rome_activity.xlsx  ROME_ACTIVITY_ALLRANK_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Rome_activity.xlsx  ROME_ACTIVITY_MEMRANK_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Hero_trial.xlsx  HERO_TRIAL_PERSONAL_RANKING --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Hero_trial.xlsx  HERO_TRIAL_LIKE_RANKING --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Hero_trial.xlsx  HERO_TRIAL_STAGE_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Achievement.xlsx  ACHIEVEMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Treasuremap.xlsx  TREASURE_MAP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activitydrop.xlsx  ACTIVITY_DROP_DATA_AR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activitydrop.xlsx  ACTIVITY_DROP_DATA_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activitydrop.xlsx  ACTIVITY_DROP_TIME --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Kingpacks.xlsx  CHESTPACK --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_weekrank_reward.xls  ALLIANCE_WEEKRANK_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  RAMADANLOGINAWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  RAMADAN_CELEBRATE_AWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activitytime.xlsx  ACTIVITYTIME --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Operation_quest_config.xlsx  OPERATION_QUEST_CONFIG_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Operation_quest_config.xlsx  OPERATION_QUEST_CONFIG_AR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Star_lamp.xlsx  STAR_LAMP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Groupbuy.xls  GROUPBUY_GOOD_CONF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Exchange_store.xlsx  EXCHANGE_STORE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activityshow.xlsx  ACTIVITY_SHOW_TIME --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_COMSUM_IOS --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_RECHARGE_IOS --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item_merge_config.xlsx  ITEM_MERGE_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGDOMPALACE_DATA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  CITYCREATE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  ITEM_ACTIVITY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activity_rank.xlsx  ACYIVITY_RANK_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_COMSUM_ANDROID --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  CUMU_RECHARGE_ANDROID --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\BadgeExchange.xlsx  BADGE_EXCHANGE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Extreme_shop.xlsx  EXTREME_SHOP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  HISTORY_CUMU_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Material_workshop.xlsx  MATERIAL_WORKSHOP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Material_workshop.xlsx  MATERIAL_WORKSHOP_MONEY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Exchange_activity.xlsx  EXCHANGE_ACTIVITY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Act_common_config.xlsx  ACT_COMMON_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\World_boss.xlsx  WORLD_BOSS_DATE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\World_boss.xlsx  WORLD_BOSS_TYPE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Playerwelfare.xlsx  ONGOING_RECHARGE_REWARD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_build_info.xlsx  ALLIANCE_BUILD_INFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_jurisdiction.xlsx  ALLIANCE_JUERISDICTION --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  ITEM_LV --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_GHARRY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_HELP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_REFRESH_GOLD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_REFRESH_GOLD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_GHARRY --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_HELP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_REFRESH_GOLD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_MAP --repeated=0 --subkey=0 --output=cs










rem 客户端配置
excel2lua_final.py excel\Alliance_science.xls  ALLIANCE_SCIENCE_DESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Army.xls  ARMYDESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Army.xls  SPECIALITYDESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Army.xls  ARMYMODEL --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILDDESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  CITYEFFECTINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  BUILDDYF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Build.xls  RESINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  RESOURCECONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map.xlsx  MAPGUIDEINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  ITEMCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Item.xls  ITEMCONFIG_BACKUP --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Lord.xls  LORDSKILLDES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Lord.xls  SKILLTREE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Mail.xlsx  MAILTYPEINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Mail.xlsx  MAILCONTENTDESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Mail.xlsx  MAILSETINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Npc.xls  NPCCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Technology.xlsx  TECHNOLOGYTREE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Technology.xlsx  TECHNOLOGYDES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Vip.xlsx  VIPPRIVILEGE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Vip.xlsx  VIPBUFF --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  LIMITACTIVITIES_SECTION --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  LIMITACTIVITIES_EVENT --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Limitactivities.xlsx  LIMITACTIVITIES_ARMYDES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Quest.xlsx  QUEST_DESCRIBE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  RECHARGEPAGEVIEW --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  RECHARGE_CLIENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Recharge.xls  RECHARGE_CLIENT_CONFIG_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  NATIONALCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  NATIONALCONFIG_EN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGOFFICIALCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGPACKSCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  OFFICIAL_BUFF_DES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\King.xls  KINGDOMPALACE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Equip.xlsx  EQUIPMENT_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Achievement.xlsx  ACHIEVEMENT_INFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Achievement.xlsx  ACHIEVEMENT_POSTINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Chat_effect.xlsx  CHATEFFECT --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activityshow.xlsx  ACTIVITY_SHOW_DATA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Star_lamp.xlsx  STAR_LAMP_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Castle_skin.xlsx  CASTLESKIN --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Kingpacks.xlsx  CHESTPACKCONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Ios_rank.xlsx  IOS_RANK_DES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Activity_rank.xlsx  ACYIVITY_RANK_DES --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Achievement.xlsx  MADAL_TYPE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Castle_namefloor.xlsx  CASTLE_NAMEFLOOR --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Achievement.xlsx  MEDAL_BUFF_TYPE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Extreme_shop.xlsx  EXTREME_SHOP_DATA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\March_effect.xlsx  MARCH_EFFECT --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\World_boss.xlsx  WORLD_BOSS_CONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Kingpacks.xlsx  CHESTPACKSHOW --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\World_boss.xlsx  WORLD_BOSS_SHOW --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Alliance_jurisdiction.xlsx  ALLIANCE_JUERISDICTION_DATA --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Login_tips.xlsx  LOGIN_TIPS --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_REFRESH_GOLD --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Escort.xlsx  ESCORT_GHARRY_DATA --repeated=0 --subkey=0 --output=cs



rem 测试数据
excel2lua_final.py excel\Map_test.xlsx  MAPOBJNUM --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map_test.xlsx  CITYREFRESH --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map_test.xlsx  RELIC --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map_test.xlsx  RESOURCE --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map_test.xlsx  RESOURCECONFIG --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Map_test.xlsx  MAPGUIDEINFO --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Pyramid_test.xlsx  PYRAMID --repeated=0 --subkey=0 --output=cs
excel2lua_final.py excel\Pyramid_test.xlsx  PYRAMID_ITEM --repeated=0 --subkey=0 --output=cs