---
--- Created by zhiwei.
--- DateTime: 2020/4/28 19:26
---

---@alias ModuleDetail table<string, RedDotDefineNode>
---@alias ModuleType table<string, RedDotDefineNode>
---@class RedDotDefine
---@field ModuleDetail ModuleDetail
---@field ModuleType ModuleType
local RedDotDefine = {}

local RedModuleType = redDef.RedModuleType

-- 定义模块类型，用下划线构造树状结构，比如妃子主界面-妃子详情
RedDotDefine.ModuleType = {
    Sign                               = "Sign",
    Mail                               = "Mail",
    Rank                               = "Rank",
    School                             = "School",
    GrowFund                           = "GrowFund",
    SevenDaily                         = "SevenDaily",
    Chat_Private                       = "ChatPrivate",
    Chat_Kingdom                       = "ChatKingdom",
    Chat_Alliance                      = "ChatAlliance",
    Chat_Global                        = "ChatGlobal",
    Tribute_Shop                       = "TributeShop",
    DailyQuest                         = "DailyQuest",          --日常
    AchievementQuest                   = "AchievementQuest",    --成就
    Questionnaire                      = "Questionnaire",
    AllianceAssemble                   = "AllianceAssemble",
    BindingAccount                     = "BindingAccount",

    Vip                                = "Vip",
    Vip_Level                          = "Vip_Level",
    Summit                             = "Summit",
    SummitSkill                        = "Summit_Skill",
    -- 妃子
    PrincessMain                       = "PrincessMain",
    Princess                           = "PrincessMain_Princess",
    Princess_Energy                    = "PrincessMain_Princess_Energy",
    Princess_Title                     = "PrincessMain_Princess_Title",
    Princess_Gift                      = "PrincessMain_Princess_Gift",
    Children                           = "PrincessMain_Children",
    Children_Inner                     = "PrincessMain_Children_Inner",
    DanceParty                         = "PrincessMain_DanceParty",
    DanceParty_Princess                = "PrincessMain_DanceParty_Princess",
    DanceParty_Join                    = "PrincessMain_DanceParty_Join",
    Marriage                           = "PrincessMain_Marriage",
    Marriage_Notice                    = "PrincessMain_Marriage_Notice",
    -- 联盟
    Alliance                           = "Alliance",
    Alliance_Build                     = "Alliance_Build",
    Alliance_Member                    = "Alliance_Member",
    Alliance_Member_Btn                = "Alliance_Member_Btn",
    Alliance_Activity                  = "Alliance_Activity",
    Alliance_TradeRoute                = "Alliance_TradeRoute",
    Dungeon                            = "Dungeon",
    Dungeon_Item                       = "Dungeon_Item",

    HeroUp                             = "HeroUp",
    HeroUp_RankTab                     = "HeroUp_RankTab",
    HeroUp_AptTab                      = "HeroUp_AptTab",
    HeroUp_SkillTab                    = "HeroUp_SkillTab",
    HeroUp_RankBtn                     = "HeroUp_RankBtn",
    HeroUp_AptBtn                      = "HeroUp_AptBtn",
    HeroUp_SkillBtn                    = "HeroUp_SkillBtn",
    Worship                            = "Worship",
    Worship_Achievement                = "Worship_Achievement",
    Worship_Achievement_TabLand        = "Worship_Achievement_TabLand",
    Worship_Achievement_Intimacy       = "Worship_Achievement_Intimacy",
    Worship_Achievement_Task           = "Worship_Achievement_Task",
    PlayEctype                         = "PlayEctype",
    PlayEctype_Corsair                 = "PlayEctype_Corsair",
    PlayEctype_Hunt                    = "PlayEctype_Hunt",
    -- 领主
    Lord                               = "Lord",
    Lord_Title                         = "Lord_Title",
    Lord_Title_Title                   = "Lord_Title_Title",
    Lord_Title_Fashion                 = "Lord_Title_Fashion",
    Lord_Dress                         = "Lord_Dress",
    Lord_Dress_Chat                    = "Lord_Dress_Chat",
    Lord_Dress_HeadBox                 = "Lord_Dress_HeadBox",
    Lord_Dress_Head                    = "Lord_Dress_Head",
    Lord_Dress_Head_Hero               = "Lord_Dress_Head_Hero",
    Lord_Dress_Head_Princess           = "Lord_Dress_Head_Princess",
    Lord_Dress_Head_Dress              = "Lord_Dress_Head_Dress",
    Lord_Dress_Page                    = "Lord_Dress_Page",
    -- 主界面右侧下拉栏
    NewFrameRight                      = "NewFrameRight",
    BloodLady                          = "NewFrameRight_BloodLady",
    BattleRoyale                       = "NewFrameRight_BattleRoyale",

    WelfareCenter                      = "NewFrameRight_WelfareCenter",
    FlashSale                          = "NewFrameRight_FlashSale",
    FlashSale_Inner                    = "NewFrameRight_FlashSale_Inner",
    CommonActivity_TimeReward          = "NewFrameRight_CommonActivityTimeReward",
    CommonActivity_TimeReward_Sub      = "NewFrameRight_CommonActivityTimeReward_Sub",
    CommonActivity_UsePropFish             = "NewFrameRight_CommonActivityUsePropFish",
    CommonActivity_UsePropBake             = "NewFrameRight_CommonActivityUsePropBake",
    CommonActivity_UsePropSuppress         = "NewFrameRight_CommonActivityUsePropSuppress",
    CommonActivity_UsePropFish_RankRewards = "NewFrameRight_CommonActivityUsePropFish_RankRewards",
    CommonActivity_UsePropBake_RankRewards = "NewFrameRight_CommonActivityUsePropBake_RankRewards",
    CommonActivity_UsePropSuppress_RankRewards = "NewFrameRight_CommonActivityUsePropSuppress_RankRewards",
    CommonActivity_Recharge            = "NewFrameRight_CommonActivityRecharge",
    CommonActivity_Recharge_Daily      = "NewFrameRight_CommonActivityRecharge_Daily",
    CommonActivity_Recharge_Add        = "NewFrameRight_CommonActivityRecharge_Add",
    CommonActivity_Recharge_AddDay     = "NewFrameRight_CommonActivityRecharge_AddDay",
    CommonActivity_Chariot             = "NewFrameRight_CommonActivity_Chariot",
    CommonActivity_Chariot_Apply       = "NewFrameRight_CommonActivity_Chariot_Apply",
    CommonActivity_Niebelungen         = "CommonActivity_Niebelungen",
    CommonActivity_Niebelungen_RankRewards = "CommonActivity_Niebelungen_RankRewards",
    CommonActivity_HeroRoad            = "NewFrameRight_CommonActivity_HeroRoad",
    CommonActivity_CrossArena            = "NewFrameRight_CommonActivity_CrossArena",

    CommonActivity_CrossActivityIntimacyAdd            = "NewFrameRight_CommonActivity_CrossActivityIntimacyAdd",
    CommonActivity_CrossActivityNationalPower            = "NewFrameRight_CommonActivity_CrossActivityNationalPower",
    CommonActivity_CrossActivityAptitudeAdd            = "NewFrameRight_CommonActivity_CrossActivityAptitudeAdd",

    Bag                                = "Bag",
    Bag_Item                           = "Bag_Item",
    Bag_Nobility                       = "Bag_Nobility",
    Bag_Nobility_Item                  = "Bag_Nobility_Item",
    Journey                            = "Journey", --寻访 改 巡游
    JourneyClue                        = "JourneyClue", --巡游线索
    Banquet                            = "Banquet",
    Banquet_Message                    = "Banquet_Message",
    Banquet_Message_Attend             = "Banquet_Message_Attend",
    Friend                             = "Friend",
    Friend_Inner                       = "Friend_Inner",
    Privilege                          = "Privilege",
    Privilege_Year                     = "Privilege_Year",
    Privilege_Month                    = "Privilege_Month",
    Interior                           = "Interior",
    Interior_Levy                      = "Interior_Levy",
    Interior_Affairs                   = "Interior_Affairs",
    HeroArena                          = "HeroArena",
    HeroArena_Record                   = "HeroArena_Record",
    Cabinet                            = "Cabinet",
    Cabinet_Contest                    = "Cabinet_Contest",
    DirectShop                         = "DirectShop",
    DirectShop_Outside                 = "DirectShop_Outside",
    BoatTreasure                       = "BoatTreasure",
    BoatTreasure_RankRewards           = "BoatTreasure_RankRewards",
}

---@class RedDotDefineNode
---@field parentName string @红点生成位置，如果不想新建节点，可以配合offset使用
---@field ctrlName string @模块名
---@field funcName string @获取红点方法名，不填默认为GetRedDotCount，为了兼容同一个ctrl，多个红点，可空
---@field showCount boolean @是否展示数字，可空
---@field offset number[] @红点预制相对于parent的偏移，可空
---@field prefabName string @预制名，可空

local ModuleType = RedDotDefine.ModuleType
RedDotDefine.ModuleDetail = {
    [ModuleType.DailyQuest]                         = { parentName = "BtnDaily", ctrlName = "QuestCtrl", funcName = "GetDailyQuestRedDotCount",offset  = { 20, 36 }, unlockType = ViewDefine.ViewFunctionType.MISSIONOFDAY },
    [ModuleType.AchievementQuest]                   = { parentName = "BtnAch", ctrlName = "QuestCtrl", funcName = "GetAchievementRedDotCount", offset = { 20, 36 }, unlockType = ViewDefine.ViewFunctionType.ACHIVEMENT },
    --主界面右边下拉栏
    [ModuleType.NewFrameRight]                      = { parentName = "RedPoint", ctrlName = "NewFramCtrl", funcName = "GetRedDotCount" , offset = { 25, -16 },},
    [ModuleType.BloodLady]                          = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "BloodLadyCtrl", funcName = "GetRedDot" },
    [ModuleType.BattleRoyale]                          = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "BattleRoyaleCtrl", funcName = "GetRedDot" },
    
    [ModuleType.WelfareCenter]                      = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "PrivilegeCardCtrl", funcName = "GetMainViewRedDotCount" },
    [ModuleType.CommonActivity_TimeReward]          = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByType" },
    [ModuleType.CommonActivity_UsePropFish]             = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "PropActivityCtrl", funcName = "GetTotalRedDotCount" },
    [ModuleType.CommonActivity_UsePropBake]             = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "PropActivityCtrl", funcName = "GetTotalRedDotCount" },
    [ModuleType.CommonActivity_UsePropSuppress]         = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "PropActivityCtrl", funcName = "GetTotalRedDotCount" },
    [ModuleType.CommonActivity_Recharge]            = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByType" },
    [ModuleType.CommonActivity_Chariot]             = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "ChariotCtrl", funcName = "GetRedDot" },
    [ModuleType.CommonActivity_Niebelungen]         = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "BoatTreasureCtrl", funcName = "GetRedDot" },
    [ModuleType.BoatTreasure]                    = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CrossArenaCtrl", funcName = "GetCrossArenaRedCount" },
    [ModuleType.Questionnaire]                      = { parentName = "ImgRed", ctrlName = "QuestionnaireCtrl", funcName = "GetRedDotCount" },
    [ModuleType.AllianceAssemble]                   = { parentName = "ImgRed", ctrlName = "AllianceAssembleCtrl", funcName = "GetRedDotCount" },
    [ModuleType.BindingAccount]                     = { parentName = "ImgRed", ctrlName = "SettingCtrl", funcName = "GetRedDotCount" },
    -- 妃子二级界面
    [ModuleType.PrincessMain]                       = { parentName = "ImgRed", ctrlName = "princessCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.PRINCESSSYSTEM },
    [ModuleType.Princess]                           = { parent = ModuleType.PrincessMain, parentName = "ImgRed", ctrlName = "princessCtrl", funcName = "GetPrincessRedDotNum", prefabName = "RedDotItemScene" },
    [ModuleType.Princess_Energy]                    = { parent = ModuleType.Princess, parentName = "BtnRandomLove", ctrlName = "princessCtrl", funcName = "GetEnergyNum", offset = { 100, 30 } },
    [ModuleType.Princess_Title]                     = { parent = ModuleType.Princess, parentName = "BtnPrincessTitle", ctrlName = "princessCtrl", funcName = "GetTitleRedDot", offset = { 30, 30 } },
    [ModuleType.Princess_Gift]                      = { parent = ModuleType.Princess, parentName = "BtnTabGift", ctrlName = "princessCtrl", funcName = "GetGiftRedDot", offset = { 145, 20 } },
    [ModuleType.DanceParty]                         = { parent = ModuleType.PrincessMain, parentName = "ImgRed", ctrlName = "DancingPartyCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.DANCE },
    [ModuleType.DanceParty_Princess]                = { parent = ModuleType.DanceParty, parentName = "ImgRed", ctrlName = "DancingPartyCtrl", funcName = "GetStateRedDot", offset = { 23.3, 39.9 } },
    [ModuleType.DanceParty_Join]                    = { parent = ModuleType.DanceParty, parentName = "ImgRed", ctrlName = "DancingPartyCtrl", funcName = "GetJoinRedDot", },
    [ModuleType.Marriage]                           = { parent = ModuleType.PrincessMain, parentName = "ImgRed", ctrlName = "MarriageCtrl", funcName = "GetMarriageRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.MARRIAGE },
    [ModuleType.Marriage_Notice]                    = { parent = ModuleType.Marriage, parentName = "RedDot", ctrlName = "MarriageCtrl", funcName = "GetMarriageNoticeRedDot" },
    [ModuleType.Children]                           = { parent = ModuleType.PrincessMain,  parentName = "ImgRed", ctrlName = "ChildrenCtrl", funcName = "GetChildrenMainCityRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.CHILDSYSTEM },
    [ModuleType.Children_Inner]                     = { parent = ModuleType.Children, parentName = "ImgRed", ctrlName = "ChildrenCtrl", funcName = "GetChildrenRedDot" },
    [ModuleType.Cabinet]                            = { parentName = "ImgRed", ctrlName = "HeroContestCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene" },
    [ModuleType.Cabinet_Contest]                    = { parent = ModuleType.Cabinet, parentName = "ImgRed", ctrlName = "HeroContestCtrl", funcName = "GetStateRedDot", offset = { 84.4, 25.8 } },
    [ModuleType.Summit]                             = { parentName = "ImgRed", ctrlName = "SummitCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene" },
    [ModuleType.SummitSkill]                        = { parent = ModuleType.Summit, parentName = "BtnSkill", ctrlName = "SummitCtrl", funcName = "GetSkillRedDotCount", offset = { 30, 30 } },
    [ModuleType.Alliance]                           = { parentName = "ImgRed", ctrlName = "AllianceCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.ALLIANCE },
    [ModuleType.Alliance_Activity]                  = { parent = ModuleType.Alliance,parentName = "BtnActivity", ctrlName = "SpecialActivityCtrl", funcName = "GetAllianceActivityRed", offset = { 40, 40 } },
    [ModuleType.Alliance_TradeRoute]                = { parent = ModuleType.Alliance,parentName = "BtnBuilding", ctrlName = "TradeRouteCtrl", funcName = "GetTradeRouteRed", offset = { 40, 40 } },
    [ModuleType.Alliance_Build]                     = { parent = ModuleType.Alliance,parentName = "BtnBuild", ctrlName = "AllianceCtrl", funcName = "GetBuildRedDot", offset = { 40, 40 } },
    [ModuleType.Alliance_Member]                    = { parent = ModuleType.Alliance,parentName = "BtnCheckMore", offset = { 40, 40 }, mid = RedModuleType.Alliance, rid = redDef.RedAllianceType.apply },
    [ModuleType.Alliance_Member_Btn]                = { parent = ModuleType.Alliance_Member,parentName = "BtnApplyList", offset = { 30, 30 }, mid = RedModuleType.Alliance, rid = redDef.RedAllianceType.apply },
    [ModuleType.Journey]                            = { parentName = "ImgRed", ctrlName = "JourneyCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.TRAVEL },
    [ModuleType.JourneyClue]                        = { parentName = "BtnPrincessClue", offset = { 24, 24 }, mid = RedModuleType.Journey, rid = redDef.RedJourneyType.clue },
    [ModuleType.Banquet]                            = { parentName = "ImgRed", ctrlName = "BanquetCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.BANQUEST },
    [ModuleType.Banquet_Message]                    = { parent = ModuleType.Banquet, parentName = "BtnMessage", ctrlName = "BanquetCtrl", funcName = "GetAttendRewardRedDot", offset = { 63.5, 14 } },
    [ModuleType.Banquet_Message_Attend]             = { parent = ModuleType.Banquet_Message, parentName = "BtnEnter", ctrlName = "BanquetCtrl", funcName = "GetAttendRewardRedDot", offset = { 86, 19 } },
    [ModuleType.Tribute_Shop]                       = { parentName = "ImgRed", ctrlName = "TributeCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.TRIBUTE },
    [ModuleType.School]                             = { parentName = "ImgRed", ctrlName = "schoolCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.SCHOOL },
    [ModuleType.Rank]                               = { parentName = "ImgRed", ctrlName = "RankNewCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene" },
    [ModuleType.Interior]                           = { parentName = "ImgRed", ctrlName = "InteriorCtrl", funcName = "GetInteriorRedDotCount", prefabName = "RedDotItemScene" },
    [ModuleType.Interior_Levy]                      = { parent = ModuleType.Interior, parentName = "NodeLevyRed", ctrlName = "InteriorCtrl", funcName = "GetInteriorLevyRedDotCount", },
    [ModuleType.Interior_Affairs]                   = { parent = ModuleType.Interior, parentName = "NodeAffairRed", ctrlName = "InteriorCtrl", funcName = "GetInteriorAffairsRedDotCount", },
    [ModuleType.HeroArena]                          = { parentName = "ImgRed", ctrlName = "ArenaCtrl", funcName = "GetCity2DRedDot", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.ARENA },
    [ModuleType.HeroArena_Record]                   = { parent = ModuleType.HeroArena, parentName = "NodeRed", ctrlName = "ArenaCtrl", funcName = "GetAcceptRecordRedDot", offset = { 30, 35 } },
    [ModuleType.Dungeon]                            = { parentName = "BtnDungeon", ctrlName = "AllianceDungeonCtrl", funcName = "GetAllDungeonRedDot", offset = { 40, 40 } },
    [ModuleType.Dungeon_Item]                       = { parent = ModuleType.Dungeon, parentName = "BtnAttack", ctrlName = "AllianceDungeonCtrl", funcName = "GetDungeonRedDot", offset = { 85, 25 } },
    [ModuleType.HeroUp]                             = { parentName = "ImgRed", ctrlName = "heroCtrl", funcName = "GetHeroUpDotCount" },
    [ModuleType.HeroUp_RankTab]                     = { parent = ModuleType.HeroUp, parentName = "ImgRedRankTab", ctrlName = "heroCtrl", funcName = "GetHeroRankUpDotCount" },
    [ModuleType.HeroUp_AptTab]                      = { parent = ModuleType.HeroUp, parentName = "ImgRedAptTab", ctrlName = "heroCtrl", funcName = "GetHeroAptUpDotCount" },
    [ModuleType.HeroUp_SkillTab]                    = { parent = ModuleType.HeroUp, parentName = "ImgRedSkillTab", ctrlName = "heroCtrl", funcName = "GetHeroSkillUpDotCount" },
    [ModuleType.HeroUp_RankBtn]                     = { parent = ModuleType.HeroUp, parentName = "ImgRedRankBtn", ctrlName = "heroCtrl", funcName = "GetHeroRankUpDotCount" },
    [ModuleType.HeroUp_AptBtn]                      = { parent = ModuleType.HeroUp, parentName = "ImgRedAptBtn", ctrlName = "heroCtrl", funcName = "GetHeroAptUpByTargetDotCount" },
    [ModuleType.HeroUp_SkillBtn]                    = { parent = ModuleType.HeroUp, parentName = "ImgRedSkllBtn", ctrlName = "heroCtrl", funcName = "GetHeroSkillUpByTargetDotCount" },
    [ModuleType.Mail]                               = { parentName = "ImgRed", ctrlName = "mailCtrl", funcName = "GetTotalDotCount" },
    [ModuleType.Vip]                                = { parentName = "ImgRed", ctrlName = "vipCtrl", funcName = "GetTotalDotCount" },
    [ModuleType.Vip_Level]                          = { parent = ModuleType.Vip, parentName = "ImgRed", ctrlName = "vipCtrl", funcName = "GetLevelDotCount" },
    [ModuleType.Worship]                            = { parentName = "ImgRed", ctrlName = "worshipCtrl", funcName = "GetTotalDotCount", prefabName = "RedDotItemScene", unlockType = ViewDefine.ViewFunctionType.WORSHIP },
    [ModuleType.Worship_Achievement]                = { parent = ModuleType.Worship, parentName = "ImgRed", ctrlName = "worshipCtrl", funcName = "GetAchievementDotCount" },
    [ModuleType.Worship_Achievement_TabLand]        = { parent = ModuleType.Worship_Achievement, parentName = "NodeRed", ctrlName = "worshipCtrl", funcName = "GetAchievementTabDotCount" },
    [ModuleType.Worship_Achievement_Intimacy]       = { parent = ModuleType.Worship_Achievement, parentName = "NodeRed", ctrlName = "worshipCtrl", funcName = "GetAchievementTabDotCount" },
    [ModuleType.Worship_Achievement_Task]           = { parent = ModuleType.Worship_Achievement, parentName = "ImgRed", ctrlName = "worshipCtrl", funcName = "GetAchievementTaskDotCount" },
    [ModuleType.PlayEctype]                         = { parentName = "ImgRed", ctrlName = "corsairCtrl", funcName = "GetTotalDotCount", prefabName = "RedDotItemScene", },
    [ModuleType.PlayEctype_Corsair]                 = { parent = ModuleType.PlayEctype, parentName = "ImgRed", ctrlName = "corsairCtrl", funcName = "GetCorsairDotCount", prefabName = "RedDotItemScene", },
    [ModuleType.PlayEctype_Hunt]                    = { parent = ModuleType.PlayEctype, parentName = "ImgRed", ctrlName = "HeroHuntCtrl", funcName = "GetRedDot", prefabName = "RedDotItemScene", },
    [ModuleType.Lord]                               = { parentName = "BtnHead", ctrlName = "DressupCtrl", funcName = "HaveAnyNewDress", offset = { 25, 30 } },
    [ModuleType.Lord_Title]                         = { parent = ModuleType.Lord, parentName = "BtnLordTitle", ctrlName = "DressupCtrl", funcName = "HaveNewTitle", offset = { 30, 30 } },
    [ModuleType.Lord_Title_Title]                   = { parent = ModuleType.Lord_Title, parentName = "NodeRed", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressTitle",},
    [ModuleType.Lord_Title_Fashion]                 = { parent = ModuleType.Lord_Title, parentName = "NodeRed", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressFashion",},
    [ModuleType.Lord_Dress]                         = { parent = ModuleType.Lord, parentName = "BtnDress", ctrlName = "DressupCtrl", funcName = "HaveNewOther", offset = { 30, 30 } },
    [ModuleType.Lord_Dress_Chat]                    = { parent = ModuleType.Lord_Dress, parentName = "NodeRed", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressChat",},
    [ModuleType.Lord_Dress_HeadBox]                 = { parent = ModuleType.Lord_Dress, parentName = "NodeRed", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressHeadBox",},
    [ModuleType.Lord_Dress_Head]                    = { parent = ModuleType.Lord_Dress, parentName = "NodeRed", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressHead",},
    [ModuleType.Lord_Dress_Page]                    = { parent = ModuleType.Lord_Dress, parentName = "ImgIcon", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDress", offset = { 20, 20 } },
    [ModuleType.Lord_Dress_Head_Hero]               = { parent = ModuleType.Lord_Dress_Head, parentName = "ImgItem", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressHeadHero", offset = { 90, 23 } },
    [ModuleType.Lord_Dress_Head_Princess]           = { parent = ModuleType.Lord_Dress_Head, parentName = "ImgItem", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressHeadPrincess", offset = { 90, 23 } },
    [ModuleType.Lord_Dress_Head_Dress]              = { parent = ModuleType.Lord_Dress_Head, parentName = "ImgItem", ctrlName = "DressupCtrl", funcName = "HaveSpeNewDressHeadDress", offset = { 90, 23 } },
    [ModuleType.CommonActivity_TimeReward_Sub]      = { parent = ModuleType.CommonActivity_TimeReward, parentName = "ImgRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByPid" },
    [ModuleType.CommonActivity_UsePropFish_RankRewards] = { parent = ModuleType.CommonActivity_UsePropFish, parentName = "ImgRedRank", ctrlName = "PropActivityCtrl", funcName = "GetRankRewardsDotCount" },
    [ModuleType.CommonActivity_UsePropBake_RankRewards] = { parent = ModuleType.CommonActivity_UsePropBake, parentName = "ImgRedRank", ctrlName = "PropActivityCtrl", funcName = "GetRankRewardsDotCount" },
    [ModuleType.CommonActivity_UsePropSuppress_RankRewards] = { parent = ModuleType.CommonActivity_UsePropSuppress, parentName = "ImgRedRank", ctrlName = "PropActivityCtrl", funcName = "GetRankRewardsDotCount" },
    [ModuleType.CommonActivity_Recharge_Daily]      = { parent = ModuleType.CommonActivity_Recharge, parentName = "NodeRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByPid" },
    [ModuleType.CommonActivity_Recharge_Add]        = { parent = ModuleType.CommonActivity_Recharge, parentName = "NodeRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByPid" },
    [ModuleType.CommonActivity_Recharge_AddDay]     = { parent = ModuleType.CommonActivity_Recharge, parentName = "NodeRed", ctrlName = "CommonActivityCtrl", funcName = "GetRedDotCountByPid" },
    [ModuleType.CommonActivity_Chariot_Apply]       = { parent = ModuleType.CommonActivity_Chariot, parentName = "BtnApply", ctrlName = "ChariotCtrl", funcName = "GetApplyRedDot", offset = { 105, 27 } },
    [ModuleType.CommonActivity_Niebelungen_RankRewards] = { parent = ModuleType.CommonActivity_Niebelungen, parentName = "BtnRankReward", ctrlName = "NiebelungenCtrl", funcName = "GetRankRewardsRedDot", offset = { 105, 27 } },
    [ModuleType.BoatTreasure_RankRewards] = { parent = ModuleType.BoatTreasure, parentName = "NodeRed", ctrlName = "BoatTreasureCtrl", funcName = "GetRankRewardsRedDot", offset = { 105, 27 } },
    [ModuleType.Bag]                                = { parentName = "BtnBag", ctrlName = "BagCtrl", funcName = "GetBagDotCount", offset = { 20, 36 } },
    [ModuleType.Bag_Item]                           = { parent = ModuleType.Bag, parentName = "NodeRed", ctrlName = "BagCtrl", funcName = "GetItemNewRed", },
    [ModuleType.Bag_Nobility]                       = { parent = ModuleType.Bag, parentName = "NodeRed", ctrlName = "MaterialsStoreCtrl", funcName = "GetBagNobilityDotCount", },
    [ModuleType.Bag_Nobility_Item]                  = { parent = ModuleType.Bag_Nobility, parentName = "BtnOk", ctrlName = "MaterialsStoreCtrl", funcName = "GetBagNobilityDotCount", offset = { 65, 10 } },
    [ModuleType.Chat_Private]                       = { parentName = "NodeRed", ctrlName = "ChatCtrl", funcName = "GetPrivateChatDotCount" },
    [ModuleType.Chat_Kingdom]                       = { parentName = "NodeRed", ctrlName = "ChatCtrl", funcName = "GetKingdomChatDotCount" },
    [ModuleType.Chat_Alliance]                      = { parentName = "NodeRed", ctrlName = "ChatCtrl", funcName = "GetAllianceChatDotCount" },
    [ModuleType.Chat_Global]                        = { parentName = "NodeRed", ctrlName = "ChatCtrl", funcName = "GetGlobalChatDotCount" },
    [ModuleType.GrowFund]                           = { parentName = "ImgRed", ctrlName = "SpecialActivityCtrl", funcName = "GetGrowFundRedCount" },
    [ModuleType.Friend]                             = { parentName = "BtnFriend", ctrlName = "FriendCtrl", funcName = "GetFriendRedDotCount", offset = { 28, 40 }, showCount = true, unlockType = ViewDefine.ViewFunctionType.FRIENDLYNATION },
    [ModuleType.Friend_Inner]                       = { parent = ModuleType.Friend, parentName = "BtnNew", ctrlName = "FriendCtrl", funcName = "GetFriendRedDotCount", offset = { 20, 30 }, showCount = true },
    [ModuleType.Privilege]                          = { parentName = "ImgRed", ctrlName = "PrivilegeCardCtrl", funcName = "GetRedDotCount" },
    [ModuleType.Privilege_Year]                     = { parent = ModuleType.Privilege, parentName = "NodeRed", ctrlName = "PrivilegeCardCtrl", funcName = "GetYearRedDotCount", },
    [ModuleType.Privilege_Month]                    = { parent = ModuleType.Privilege, parentName = "NodeRed", ctrlName = "PrivilegeCardCtrl", funcName = "GetMonthRedDotCount", },
    [ModuleType.Sign]                               = { parentName = "NodeRed", ctrlName = "SignInCtrl", funcName = "GetSignRedDot", },
    [ModuleType.FlashSale]                          = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "SpecialActivityCtrl", funcName = "GetFlashSaleRedCount" },
    [ModuleType.FlashSale_Inner]                    = { parent = ModuleType.FlashSale, parentName = "RedDot", ctrlName = "SpecialActivityCtrl", funcName = "GetFlashSaleItemRedCount" },
    [ModuleType.SevenDaily]                         = { parentName = "ImgRed", ctrlName = "SevenDailyCtr", funcName = "GetRedDot" },
    [ModuleType.DirectShop]                         = { parentName = "NodeRed", ctrlName = "SpecialActivityCtrl", funcName = "GetDirectShopRed" },
    [ModuleType.DirectShop_Outside]                 = { parent = ModuleType.DirectShop, parentName = "BtnStore", ctrlName = "SpecialActivityCtrl", funcName = "GetDirectShopRed", offset = { 28, 40 }, },
    [ModuleType.CommonActivity_HeroRoad]            = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "HeroRoadCtrl", funcName = "GetRedCount" },
    [ModuleType.CommonActivity_CrossArena]       = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CrossArenaCtrl", funcName = "GetCrossArenaRedCount" },

    [ModuleType.CommonActivity_CrossActivityIntimacyAdd]       = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CrossActivityCtrl", funcName = "GetRedCount" },
    [ModuleType.CommonActivity_CrossActivityNationalPower]       = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CrossActivityCtrl", funcName = "GetRedCount" },
    [ModuleType.CommonActivity_CrossActivityAptitudeAdd]       = { parent = ModuleType.NewFrameRight, parentName = "ImgRed", ctrlName = "CrossActivityCtrl", funcName = "GetRedCount" },
}

return RedDotDefine